

services:
  web:
    image: ghcr.io/ake144/user-management:latest
    container_name: nextjs_app
    environment:
      - DATABASE_URL=postgresql://myuser:your_secure_password@postgres_db:5432/myapp
   

    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "3000:3000"
    restart: always

  db:
    image: postgres:16
    container_name: postgres_db
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-myapp}
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-supersecret}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
